Repository microsoft/VFSForGit, pull requests merged in 2019-02, with the labels that each got.

#748 Merge features/upgrade_extensibility to master
  GVFS/FastFetch/CheckoutStage.cs
  GVFS/GVFS.Common/DiskLayoutUpgrade.cs
  GVFS/GVFS.Common/FileSystem/IPlatformFileSystem.cs
  GVFS/GVFS.Common/FileSystem/PhysicalFileSystem.cs
  GVFS/GVFS.Common/GVFS.Common.csproj
  GVFS/GVFS.Common/GVFSConstants.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/GitHubUpgrader.cs
  GVFS/GVFS.Common/IProductUpgrader.cs
  GVFS/GVFS.Common/LocalGVFSConfig.cs
  GVFS/GVFS.Common/NuGetUpgrade/InstallActionInfo.cs
  GVFS/GVFS.Common/NuGetUpgrade/InstallManifest.cs
  GVFS/GVFS.Common/NuGetUpgrade/InstallManifestPlatform.cs
  GVFS/GVFS.Common/NuGetUpgrade/NuGetFeed.cs
  GVFS/GVFS.Common/NuGetUpgrade/NuGetUpgrader.cs
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.Common/ProductUpgraderFactory.cs
  GVFS/GVFS.Common/ProductUpgraderInfo.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GVFSUpgradeReminderTests.cs
  GVFS/GVFS.Installer.Windows/Setup.iss
  GVFS/GVFS.Platform.Mac/MacFileSystem.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystem.cs
  GVFS/GVFS.Service/GvfsService.cs
  GVFS/GVFS.Service/ProductUpgradeTimer.cs
  GVFS/GVFS.UnitTests.Windows/App.config
  GVFS/GVFS.UnitTests.Windows/GVFS.UnitTests.Windows.csproj
  GVFS/GVFS.UnitTests.Windows/Windows/Mock/MockGitHubUpgrader.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Mock/MockLocalGVFSConfig.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/ProductUpgraderTests.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/UpgradeOrchestratorTests.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/UpgradeOrchestratorWithGitHubUpgraderTests.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/UpgradeTests.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/UpgradeVerbTests.cs
  GVFS/GVFS.UnitTests.Windows/packages.config
  GVFS/GVFS.UnitTests/Common/InstallManifestTests.cs
  GVFS/GVFS.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs
  GVFS/GVFS.UnitTests/GVFS.UnitTests.csproj
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFileSystem.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockPlatformFileSystem.cs
  GVFS/GVFS.Upgrader/App.config
  GVFS/GVFS.Upgrader/GVFS.Upgrader.csproj
  GVFS/GVFS.Upgrader/UpgradeOrchestrator.cs
  GVFS/GVFS.Upgrader/packages.config
  GVFS/GVFS/App.config
  GVFS/GVFS/CommandLine/ConfigVerb.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
  GVFS/GVFS/CommandLine/UpgradeVerb.cs
  GVFS/GVFS/GVFS.Windows.csproj
  GVFS/GVFS/RepairJobs/RepairJob.cs
  GVFS/GVFS/packages.config
Labels: enhancement, windows

#734 Add listener for OPEN event
  GVFS/GVFS.FunctionalTests/FileSystemRunners/BashRunner.cs
  GVFS/GVFS.FunctionalTests/FileSystemRunners/CmdRunner.cs
  GVFS/GVFS.FunctionalTests/FileSystemRunners/FileSystemRunner.cs
  GVFS/GVFS.FunctionalTests/FileSystemRunners/PowerShellRunner.cs
  GVFS/GVFS.FunctionalTests/FileSystemRunners/SystemIORunner.cs
  GVFS/GVFS.FunctionalTests/Tests/GitCommands/GitRepoTests.cs
  GVFS/GVFS.FunctionalTests/Tests/GitCommands/StatusTests.cs
  ProjFS.Mac/PrjFSKext/KauthHandler.cpp
Labels: git-correctness, macOS

#753 Bug Bash Fixes [into master]
  GVFS/GVFS.Common/NuGetUpgrade/NuGetUpgrader.cs
  GVFS/GVFS.Upgrader/UpgradeOrchestrator.cs
Labels: windows

#764 Log ring when querying for upgrades on the background timer
  GVFS/GVFS.Service/ProductUpgradeTimer.cs
Labels: live-site, polish, windows

#765 Log ring when querying for upgrades on the background timer [M147 port]
  GVFS/GVFS.Service/ProductUpgradeTimer.cs
Labels: live-site, polish, windows

#512 Load SSL certificate according to git config
  GVFS/GVFS.Common/FileSystem/PhysicalFileSystem.cs
  GVFS/GVFS.Common/GVFS.Common.csproj
  GVFS/GVFS.Common/Git/GitAuthentication.cs
  GVFS/GVFS.Common/Git/GitConfigHelper.cs
  GVFS/GVFS.Common/Git/GitConfigSetting.cs
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/Git/GitSsl.cs
  GVFS/GVFS.Common/Http/ConfigHttpRequestor.cs
  GVFS/GVFS.Common/Http/GitObjectsHttpRequestor.cs
  GVFS/GVFS.Common/Http/HttpRequestor.cs
  GVFS/GVFS.Common/Tracing/ITracer.cs
  GVFS/GVFS.Common/Tracing/JsonTracer.cs
  GVFS/GVFS.Common/X509Certificates/CertificateVerifier.cs
  GVFS/GVFS.Common/X509Certificates/SystemCertificateStore.cs
  GVFS/GVFS.UnitTests/Common/Git/GitSslTests.cs
  GVFS/GVFS.UnitTests/Common/GitConfigHelperTests.cs
  GVFS/GVFS.UnitTests/GVFS.UnitTests.csproj
  GVFS/GVFS.UnitTests/Git/GitAuthenticationTests.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockTracer.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFile.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFileSystem.cs
  GVFS/GVFS.UnitTests/Mock/ReusableMemoryStream.cs
  GVFS/GVFS/CommandLine/CloneVerb.cs
Labels: enhancement

#683 Use a single LibGit2Repo for multiple requests, dispose if left unused
  GVFS/GVFS.Common/Git/GitRepo.cs
  GVFS/GVFS.Common/Git/LibGit2RepoInvoker.cs
  GVFS/GVFS.Common/LibGit2RepoPool.cs
  GVFS/GVFS.Common/Maintenance/PackfileMaintenanceStep.cs
  GVFS/GVFS.UnitTests/Common/LibGit2RepoInvokerTests.cs
  GVFS/GVFS.UnitTests/Maintenance/PackfileMaintenanceStepTests.cs
Labels: performance

#749 Update git to include trace2 V7
  GVFS/GVFS.Build/GVFS.props
Labels: live-site

#779 Update git to include trace2 v7 and process walk fix.
  GVFS/GVFS.Build/GVFS.props
Labels: live-site, reliability

#776 [merge to M147] Log GVFS.Service ACL exceptions, and fix upgrade log directory ACL issue
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DiagnoseTests.cs
  GVFS/GVFS.Service/GvfsService.cs
Labels: windows

#772 Rephrase ProjFS error messaging
  GVFS/GVFS.Common/InstallerPreRunChecker.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/UpgradeVerbTests.cs
Labels: polish, port-from-release-branch, windows

#777 [merge to master] Log GVFS.Service ACL exceptions, and fix upgrade log directory ACL issue
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DiagnoseTests.cs
  GVFS/GVFS.Service/GvfsService.cs
Labels: port-from-release-branch, windows

#775 Improve upgrader logging
  GVFS/GVFS.Common/Enlistment.cs
  GVFS/GVFS.Common/GitHubUpgrader.cs
  GVFS/GVFS.Common/NuGetUpgrade/NuGetUpgrader.cs
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs
  GVFS/GVFS.Upgrader/UpgradeOrchestrator.cs
Labels: live-site, port-from-release-branch, windows

#782 Rephrase ProjFS error messaging
  GVFS/GVFS.Common/InstallerPreRunChecker.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/UpgradeVerbTests.cs
Labels: polish, windows

#783 Upgrader messaging m147
  GVFS/GVFS.Common/Enlistment.cs
  GVFS/GVFS.Common/GitHubUpgrader.cs
  GVFS/GVFS.Common/NuGetUpgrade/NuGetUpgrader.cs
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs
  GVFS/GVFS.Upgrader/UpgradeOrchestrator.cs
Labels: live-site, windows

#773 Better feedback and fixes for Upgrade Scenario
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/InstallerPreRunChecker.cs
  GVFS/GVFS.Common/Maintenance/GitMaintenanceStep.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.UnitTests/Git/GitProcessTests.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS.Upgrader/UpgradeOrchestrator.cs
Labels: bug, macOS, port-from-release-branch, reliability, windows

#784 Better feedback and fixes for Upgrade Scenario M147
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/InstallerPreRunChecker.cs
  GVFS/GVFS.Common/Maintenance/GitMaintenanceStep.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.UnitTests/Git/GitProcessTests.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS.Upgrader/UpgradeOrchestrator.cs
Labels: bug, macOS, reliability, windows

#787 Stop reading ring info from Nuget feedurl
  GVFS/GVFS.Common/GitHubUpgrader.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/ProductUpgraderTests.cs
Labels: port-from-release-branch, windows

#789 Stop reading ring info from Nuget feedurl
  GVFS/GVFS.Common/GitHubUpgrader.cs
  GVFS/GVFS.UnitTests.Windows/Windows/Upgrader/ProductUpgraderTests.cs
Labels: windows

#796 GetInsertionIndex should include the entry's name when it throws an InvalidOperationException
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.SortedFolderEntries.cs
Labels: live-site, macOS, windows

#806 Set feed url based on upgrade ring during installer [master]
  GVFS/GVFS.Installer.Windows/Setup.iss
Labels: enhancement, port-from-release-branch, windows

#803 Set feed url based on upgrade ring during installer [M147]
  GVFS/GVFS.Installer.Windows/Setup.iss
Labels: enhancement, windows

#812 Provide a more actionable "unsupported features" message for Server 2016 users
  GVFS/GVFS.Platform.Windows/ProjFSFilter.cs
Labels: live-site, polish, windows

#822 Consume new Git: Contains fixes to preserve system config during Git installation [M147]
  GVFS/GVFS.Build/GVFS.props
Labels: enhancement, windows

#823 Consume new Git: Contains fixes to preserve system config during Git installation
  GVFS/GVFS.Build/GVFS.props
Labels: enhancement, port-from-release-branch, windows

#824 Return result code when process is stopping [M147]
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/Maintenance/GitMaintenanceStep.cs
Labels: bug

#746 Call git-credential approve on successful credential usage
  GVFS/GVFS.Common/Git/GitAuthentication.cs
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/Http/HttpRequestor.cs
  GVFS/GVFS.UnitTests/Git/GitAuthenticationTests.cs
  GVFS/GVFS.UnitTests/Mock/Git/MockGitProcess.cs
Labels: bug

#840 [releases/shipped] Use a new log directory for upgrade logs to avoid ACL issues
  GVFS/GVFS.Common/FileSystem/IPlatformFileSystem.cs
  GVFS/GVFS.Common/FileSystem/PhysicalFileSystem.cs
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.Common/ProductUpgraderInfo.Shared.cs
  GVFS/GVFS.Platform.Mac/MacFileSystem.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystem.cs
  GVFS/GVFS.Service/GvfsService.cs
  GVFS/GVFS.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFileSystem.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockPlatformFileSystem.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
  GVFS/GVFS/CommandLine/UpgradeVerb.cs
Labels: bug, windows

#843 [cherry-pick to master] Use a new log directory for upgrade logs to avoid ACL issues
  GVFS/GVFS.Common/FileSystem/IPlatformFileSystem.cs
  GVFS/GVFS.Common/FileSystem/PhysicalFileSystem.cs
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.Common/ProductUpgraderInfo.Shared.cs
  GVFS/GVFS.Platform.Mac/MacFileSystem.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystem.cs
  GVFS/GVFS.Service/GvfsService.cs
  GVFS/GVFS.UnitTests/Common/NuGetUpgrade/NuGetUpgraderTests.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFileSystem.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockPlatformFileSystem.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
  GVFS/GVFS/CommandLine/UpgradeVerb.cs
Labels: bug, port-from-release-branch, windows

#802 Add tests for ShouldIgnoreVnodeType
  ProjFS.Mac/PrjFS.xcodeproj/project.pbxproj
  ProjFS.Mac/PrjFSKext/KauthHandler.cpp
  ProjFS.Mac/PrjFSKext/KauthHandlerTestable.hpp
  ProjFS.Mac/PrjFSKextTests/KauthHandlerTests.mm
  ProjFS.Mac/PrjFSKextTests/KextLogMock.h
Labels: mac-kernel-extension, macOS

#842 [releases/shipped] Enhance git command logging
  GVFS/GVFS.Common/Maintenance/GitMaintenanceStep.cs
  GVFS/GVFS.Common/Maintenance/LooseObjectsStep.cs
  GVFS/GVFS.Common/Maintenance/PackfileMaintenanceStep.cs
  GVFS/GVFS.Common/Maintenance/PostFetchStep.cs
  GVFS/GVFS.Common/Maintenance/PrefetchStep.cs
  GVFS/GVFS.UnitTests/Maintenance/GitMaintenanceStepTests.cs
Labels: bug

#856 Mac kext: Fix for vnode_put() panic bug, tighter invariant assertion & improved root search logic.
  ProjFS.Mac/PrjFSKext/KauthHandler.cpp
  ProjFS.Mac/PrjFSKext/VirtualizationRoots.cpp
  ProjFS.Mac/PrjFSKext/VirtualizationRoots.hpp
Labels: mac-kernel-extension, macOS, reliability
