Repository microsoft/VFSForGit, pull requests merged in 2019-05, with the labels that each got.

#1090 Replace use of Count on FileSystemTaskQueue with IsEmpty
  GVFS/GVFS.UnitTests/Common/BackgroundTaskQueueTests.cs
  GVFS/GVFS.UnitTests/Mock/Virtualization/Background/MockBackgroundTaskManager.cs
  GVFS/GVFS.Virtualization/Background/BackgroundFileSystemTaskRunner.cs
  GVFS/GVFS.Virtualization/Background/FileSystemTaskQueue.cs
  GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
Labels: affects: performance, domain: user-mode, platform: macOS

#1051 Auto-mount & UT
  GVFS.sln
  GVFS/GVFS.Common/FileSystem/PhysicalFileSystem.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.cs
  GVFS/GVFS.Platform.Windows/CurrentUser.cs
  GVFS/GVFS.Platform.Windows/GVFS.Platform.Windows.csproj
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.Service/GVFS.Service.Mac.csproj
  GVFS/GVFS.Service/GVFS.Service.Windows.csproj
  GVFS/GVFS.Service/GVFSMountProcess.Mac.cs
  GVFS/GVFS.Service/GVFSMountProcess.Windows.cs
  GVFS/GVFS.Service/GVFSService.Mac.cs
  GVFS/GVFS.Service/GVFSService.Windows.cs
  GVFS/GVFS.Service/Handlers/GetActiveRepoListHandler.cs
  GVFS/GVFS.Service/Handlers/NotificationHandler.Mac.cs
  GVFS/GVFS.Service/Handlers/NotificationHandler.Windows.cs
  GVFS/GVFS.Service/Handlers/RegisterRepoHandler.cs
  GVFS/GVFS.Service/Handlers/RequestHandler.cs
  GVFS/GVFS.Service/Handlers/UnregisterRepoHandler.cs
  GVFS/GVFS.Service/IRepoMounter.cs
  GVFS/GVFS.Service/IRepoRegistry.cs
  GVFS/GVFS.Service/Mac/org.vfsforgit.service.plist
  GVFS/GVFS.Service/Program.Mac.cs
  GVFS/GVFS.Service/RepoRegistry.cs
  GVFS/GVFS.UnitTests.Windows/GVFS.UnitTests.Windows.csproj
  GVFS/GVFS.UnitTests/GVFS.UnitTests.csproj
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFileSystem.cs
  GVFS/GVFS.UnitTests/Service/Mac/MacServiceTests.cs
  GVFS/GVFS.UnitTests/Service/RepoRegistryTests.cs
  GVFS/GVFS.Virtualization/AssemblyInfo.cs
Labels: affects: polish, platform: macOS

#1027 [POSIX] rename common Mac hook code to share with Linux
  GVFS/GVFS.NativeHooks.Common/common.h
  GVFS/GVFS.NativeHooks.Common/common.posix.cpp
  GVFS/GVFS.PostIndexChangedHook/GVFS.PostIndexChangedHook.Mac.xcodeproj/project.pbxproj
  GVFS/GVFS.ReadObjectHook/GVFS.ReadObjectHook.Mac.xcodeproj/project.pbxproj
  GVFS/GVFS.VirtualFileSystemHook/GVFS.VirtualFileSystemHook.Mac.xcodeproj/project.pbxproj
Labels: platform: linux, platform: macOS, pr: refactoring

#1101 Use published version of Service
  GVFS/GVFS.Service/Mac/org.vfsforgit.service.plist
Labels: affects: correctness, platform: macOS

#1102 Rename LocalStorageRoot
  GVFS/FastFetch/CheckoutStage.cs
  GVFS/GVFS.Common/Enlistment.cs
  GVFS/GVFS.Common/FileSystem/HooksInstaller.cs
  GVFS/GVFS.Common/GVFSEnlistment.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/Git/GitRepo.cs
  GVFS/GVFS.Common/Prefetch/BlobPrefetcher.cs
  GVFS/GVFS.Common/Prefetch/Git/DiffHelper.cs
  GVFS/GVFS.Common/Prefetch/Pipeline/FindBlobsStage.cs
  GVFS/GVFS.Mount/InProcessMount.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.UnitTests/Common/GitStatusCacheTests.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.cs
  GVFS/GVFS/CommandLine/CloneVerb.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
  GVFS/GVFS/CommandLine/GVFSVerb.cs
  GVFS/GVFS/CommandLine/MountVerb.cs
Labels: platform: linux, platform: macOS, platform: windows, pr: refactoring

#1107 Refactor for easier conversion to sqlite
  GVFS/GVFS.Common/Database/IPlaceholderData.cs
  GVFS/GVFS.Common/Database/IPlaceholderDatabase.cs
  GVFS/GVFS.Common/PlaceholderListDatabase.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout12to13Upgrade_FolderPlaceholder.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout16to17Upgrade_FolderPlaceholderValues.cs
  GVFS/GVFS.UnitTests/Common/PlaceholderDatabaseTests.cs
  GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.GitIndexParser.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.cs
Labels: pr: refactoring

#1111 Update Microsoft.Data.Sqlite packages to version 2.2.4.0
  GVFS/GVFS.FunctionalTests.Windows/GVFS.FunctionalTests.Windows.csproj
  GVFS/GVFS.FunctionalTests.Windows/packages.config
  GVFS/GVFS.FunctionalTests/GVFS.FunctionalTests.csproj
  GVFS/GVFS.Mount/GVFS.Mount.Windows.csproj
  GVFS/GVFS.Mount/packages.config
  GVFS/GVFS.PerfProfiling/GVFS.PerfProfiling.csproj
  GVFS/GVFS.PerfProfiling/packages.config
  GVFS/GVFS.UnitTests.Windows/GVFS.UnitTests.Windows.csproj
  GVFS/GVFS.UnitTests.Windows/packages.config
  GVFS/GVFS.Virtualization/GVFS.Virtualization.csproj
  GVFS/GVFS/GVFS.Windows.csproj
  GVFS/GVFS/packages.config
Labels: pr: refactoring, type: bug

#1103 Enable Rename tests on Mac and add additional tests for coverage
  GVFS/GVFS.FunctionalTests/Categories.cs
  GVFS/GVFS.FunctionalTests/FileSystemRunners/SystemIORunner.cs
  GVFS/GVFS.FunctionalTests/Program.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitFilesTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/WorkingDirectoryTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/ModifiedPathsTests.cs
  GVFS/GVFS.FunctionalTests/Tests/GitCommands/CheckoutTests.cs
Labels: platform: macOS, priority: mac-next

#1116 LooseObjectStepTests: Be more flexible with loose object count
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/LooseObjectStepTests.cs
Labels: affects: engineering, type: test-reliability

#1104 Update libgit2 native binaries and include .so for Linux
  GVFS/FastFetch/FastFetch.csproj
  GVFS/GVFS.Common/GVFS.Common.csproj
  GVFS/LibGit2Sharp.NativeBinaries.props
Labels: platform: linux, platform: macOS, platform: windows

#1110 [HOTFIX] Delete corrupt loose objects during LooseObjectsStep
  GVFS/GVFS.Common/Maintenance/LooseObjectsStep.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/LooseObjectStepTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/TestsWithEnlistmentPerTestCase.cs
  GVFS/GVFS.UnitTests/Maintenance/LooseObjectStepTests.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
Labels: affects: live-site, affects: performance

#1119 Rename WorkingDirectoryBackingRootPath constants
  GVFS/GVFS.Common/Enlistment.cs
  GVFS/GVFS.Common/GVFSEnlistment.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS/CommandLine/CloneVerb.cs
Labels: platform: linux, platform: macOS, platform: windows

#1007 Do not attempt to approve credentials for anonymous access
  GVFS/GVFS.Common/Http/HttpRequestor.cs
Labels: type: bug

#1123 [POSIX, Mac] Refactor BSD-specific values out of POSIXFileSystem
  GVFS/GVFS.Platform.Mac/MacFileSystem.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.POSIX/POSIXFileSystem.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.cs
Labels: platform: linux, platform: macOS, pr: refactoring

#1143 Add .vsconfig file to declare required VS components
  .vsconfig
  Readme.md
Labels: affects: engineering

#1131 PostFetchStep: delete and rewrite commit-graph on write error
  GVFS/GVFS.Common/Maintenance/PostFetchStep.cs
Labels: affects: live-site, affects: performance

#1147 Update functional test documentation
  AuthoringTests.md
Labels: affects: engineering, type: enhancement

#1151 Updated Service response to EnablePrjFS request
  GVFS/GVFS.Common/NamedPipes/NamedPipeServer.cs
  GVFS/GVFS.Service/Handlers/RequestHandler.cs
  GVFS/GVFS.UnitTests/Service/Mac/MacServiceTests.cs
Labels: type: bug

#1162 Relax LooseObjectStepTests from exact object counts
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/LooseObjectStepTests.cs
Labels: affects: tests, type: test-reliability

#1146 Platform native notifications - PR_1
  GVFS/GVFS.Installer.Mac/CreateMacInstaller.sh
  GVFS/GVFS.Installer.Mac/uninstall_vfsforgit.sh
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/IPC/GVFSTask.h
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/IPC/GVFSTask.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/Info.plist
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/AboutWindowController.h
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/AboutWindowController.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/AboutWindowController.xib
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/AppDelegate.h
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/AppDelegate.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/Contents.json
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/StatusItem.imageset/Contents.json
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/StatusItem.imageset/VFSForGit_16.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/StatusItem.imageset/VFSForGit_32.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/StatusItem.imageset/VFSForGit_64.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/Contents.json
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_1024.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_128.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_16.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_256-1.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_256.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_32-1.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_32.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_512-1.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_512.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Assets.xcassets/VFS For Git.appiconset/VFSForGit_64.png
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/Base.lproj/MainMenu.xib
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/StatusBarItem.h
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/StatusBarItem.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/UserNotification.h
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/UI/UserNotification.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/VFSForGit.entitlements
  GVFS/GVFS.Notifications/VFSForGit.Mac/StatusMenuItem/main.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.UnitTests/AboutWindowControllerTests.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.UnitTests/Info.plist
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.UnitTests/StatusBarItemTests.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.UnitTests/UserNotificationTests.m
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.xcodeproj/project.pbxproj
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GVFS/GVFS.Notifications/VFSForGit.Mac/VFSForGit.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GVFS/GVFS.Notifications/VFSForGit.Mac/org.vfsforgit.usernotification.plist
  Scripts/Mac/BuildGVFSForMac.sh
Labels: affects: polish, platform: macOS

#1128 [Linux] Implement update methods on Linux for placeholder files/dirs
  MirrorProvider/MirrorProvider.Linux/Program.cs
  MirrorProvider/Scripts/Linux/Build.sh
  ProjFS.Linux/PrjFSLib.Linux.Managed/Interop/ProjFS.cs
  ProjFS.Linux/PrjFSLib.Linux.Managed/NotificationType.cs
  ProjFS.Linux/PrjFSLib.Linux.Managed/ProjectionState.cs
  ProjFS.Linux/PrjFSLib.Linux.Managed/UpdateFailureCause.cs
  ProjFS.Linux/PrjFSLib.Linux.Managed/UpdateType.cs
  ProjFS.Linux/PrjFSLib.Linux.Managed/VirtualizationInstance.cs
  ProjFS.Linux/Scripts/Build.sh
  ProjFS.Linux/Scripts/GenerateConstants.sh
Labels: platform: linux

#985 Mac ProjFS: Two-path provider messages
  ProjFS.Mac/PrjFS.xcodeproj/project.pbxproj
  ProjFS.Mac/PrjFSKext/KauthHandler.cpp
  ProjFS.Mac/PrjFSKext/KauthHandlerTestable.hpp
  ProjFS.Mac/PrjFSKext/Message_Kernel.cpp
  ProjFS.Mac/PrjFSKext/Message_Kernel.hpp
  ProjFS.Mac/PrjFSKext/Message_Shared.cpp
  ProjFS.Mac/PrjFSKext/ProviderMessaging.cpp
  ProjFS.Mac/PrjFSKext/ProviderMessaging.hpp
  ProjFS.Mac/PrjFSKext/VirtualizationRoots.cpp
  ProjFS.Mac/PrjFSKext/VirtualizationRoots.hpp
  ProjFS.Mac/PrjFSKext/VirtualizationRootsPrivate.hpp
  ProjFS.Mac/PrjFSKext/VirtualizationRootsTestable.hpp
  ProjFS.Mac/PrjFSKext/public/Message.h
  ProjFS.Mac/PrjFSKext/public/PrjFSCommon.h
  ProjFS.Mac/PrjFSKext/public/PrjFSPerfCounter.h
  ProjFS.Mac/PrjFSKextTests/HandleFileOpOperationTests.mm
  ProjFS.Mac/PrjFSKextTests/HandleOperationTests.mm
  ProjFS.Mac/PrjFSKextTests/KauthHandlerTests.mm
  ProjFS.Mac/PrjFSKextTests/MessageTests.mm
  ProjFS.Mac/PrjFSKextTests/MockProc.cpp
  ProjFS.Mac/PrjFSKextTests/MockProc.hpp
  ProjFS.Mac/PrjFSKextTests/ProviderMessagingMock.cpp
  ProjFS.Mac/PrjFSKextTests/VirtualizationRootsTests.mm
  ProjFS.Mac/PrjFSLib/PrjFSLib.cpp
  ProjFS.Mac/PrjFSLib/prjfs-log/kext-perf-tracing.cpp
Labels: WIP, domain: kext, domain: user-mode, platform: macOS

#1157 GitProcess: Enable lower ProcessPriorityClass
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/Maintenance/GitMaintenanceStep.cs
Labels: affects: performance

#1178 Repack: use one thread, but allow deltas
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.UnitTests/Maintenance/PackfileMaintenanceStepTests.cs
Labels: affects: performance

#1194 Mac: Refactor testShouldHandleFileOpEvent test:
  ProjFS.Mac/PrjFSKextTests/KauthHandlerTests.mm
Labels: domain: kext, platform: macOS, type: test-reliability

#1190 Add notarize shell script for notarizing the kext with Apple
  Scripts/Mac/notarize.sh
Labels: affects: engineering, platform: macOS

#1084 Support alternate names for the .gvfs folder
  GVFS/GVFS.Common/DiskLayoutUpgrade.cs
  GVFS/GVFS.Common/GVFSConstants.cs
  GVFS/GVFS.Common/GVFSEnlistment.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/Git/GitRepo.cs
  GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs
  GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj
  GVFS/GVFS.FunctionalTests/GVFSTestConfig.cs
  GVFS/GVFS.FunctionalTests/Program.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/CloneTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DehydrateTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/MountTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/UnmountTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSFunctionalTestEnlistment.cs
  GVFS/GVFS.Hooks/GVFS.Hooks.Mac.csproj
  GVFS/GVFS.Hooks/HooksPlatform/GVFSHooksPlatform.Mac.cs
  GVFS/GVFS.Hooks/HooksPlatform/GVFSHooksPlatform.POSIX.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.Shared.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout11to12Upgrade_SharedLocalCache.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout12to13Upgrade_FolderPlaceholder.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout13to14Upgrade_BlobSizes.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout14to15Upgrade_ModifiedPaths.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout16to17Upgrade_FolderPlaceholderValues.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout7to8Upgrade_NewOperationType.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout8to9Upgrade_RepoMetadataToJson.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout9to10Upgrade_BackgroundAndPlaceholderListToFileBased.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.Shared.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.UnitTests/Common/GitStatusCacheTests.cs
  GVFS/GVFS.UnitTests/Git/GVFSGitObjectsTests.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
  GVFS/GVFS/CommandLine/GVFSVerb.cs
  GVFS/GVFS/CommandLine/LogVerb.cs
Labels: platform: linux

#1098 Update PrjFSKextLogDaemon to forward messages to GitServiceDaemon
  GVFS/GVFS.NativeHooks.Common/common.h
  GVFS/GVFS.NativeHooks.Common/common.posix.cpp
  GVFS/GVFS.PostIndexChangedHook/GVFS.PostIndexChangedHook.Mac.xcodeproj/project.pbxproj
  GVFS/GVFS.PostIndexChangedHook/GVFS.PostIndexChangedHook.Windows.vcxproj
  GVFS/GVFS.ReadObjectHook/GVFS.ReadObjectHook.Mac.xcodeproj/project.pbxproj
  GVFS/GVFS.ReadObjectHook/GVFS.ReadObjectHook.Windows.vcxproj
  GVFS/GVFS.ReadObjectHook/packet.cpp
  GVFS/GVFS.VirtualFileSystemHook/GVFS.VirtualFileSystemHook.Mac.xcodeproj/project.pbxproj
  GVFS/GVFS.VirtualFileSystemHook/GVFS.VirtualFileSystemHook.Windows.vcxproj
  ProjFS.Mac/PrjFS.xcodeproj/project.pbxproj
  ProjFS.Mac/PrjFS.xcodeproj/xcshareddata/xcschemes/Build All.xcscheme
  ProjFS.Mac/PrjFSKext/public/PrjFSCommon.h
  ProjFS.Mac/PrjFSKextLogDaemon/PrjFSKextLogDaemon.cpp
  ProjFS.Mac/PrjFSLib/Json/JsonWriter.cpp
  ProjFS.Mac/PrjFSLib/Json/JsonWriter.hpp
  ProjFS.Mac/PrjFSLib/PrjFSLib.cpp
  ProjFS.Mac/PrjFSLibTests/Info.plist
  ProjFS.Mac/PrjFSLibTests/JsonWriterTests.mm
  ProjFS.Mac/Scripts/Build.sh
  ProjFS.Mac/Scripts/GeneratePrjFSVersionHeader.sh
Labels: affects: live-site, platform: macOS

#1198 Remove all reference to looseObjectCount in LooseObjectStepTests
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/LooseObjectStepTests.cs
Labels: platform: linux, platform: macOS, platform: windows, type: test-reliability

#1189 Improve Linux event-handling robustness and allow provider-generated events
  ProjFS.Linux/PrjFSLib.Linux.Managed/VirtualizationInstance.cs
Labels: platform: linux

#1206 Really really fix LooseObjectStepTests by unmounting
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/LooseObjectStepTests.cs
Labels: affects: engineering, affects: tests, type: test-reliability

#1213 Prefetch tests: Delete multi-pack-index before indexing a pack
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbWithoutSharedCacheTests.cs
Labels: affects: tests, domain: git

#1140 Sqlite placeholders
  GVFS/GVFS.Common/Database/GVFSDatabase.cs
  GVFS/GVFS.Common/Database/GVFSDatabaseException.cs
  GVFS/GVFS.Common/Database/IDbCommandExtensions.cs
  GVFS/GVFS.Common/Database/IDbConnectionFactory.cs
  GVFS/GVFS.Common/Database/IGVFSConnectionPool.cs
  GVFS/GVFS.Common/Database/IPlaceholderCollection.cs
  GVFS/GVFS.Common/Database/IPlaceholderData.cs
  GVFS/GVFS.Common/Database/PlaceholderTable.cs
  GVFS/GVFS.Common/Database/SqliteDatabase.cs
  GVFS/GVFS.Common/DiskLayoutUpgrades/DiskLayoutUpgrade.cs
  GVFS/GVFS.Common/DiskLayoutUpgrades/DiskLayoutUpgrade_SqlitePlaceholders.cs
  GVFS/GVFS.Common/DiskLayoutUpgrades/DiskLayoutVersion.cs
  GVFS/GVFS.Common/GVFS.Common.csproj
  GVFS/GVFS.Common/GVFSConstants.cs
  GVFS/GVFS.Common/LegacyPlaceholderListDatabase.cs
  GVFS/GVFS.FunctionalTests.Windows/GVFS.FunctionalTests.Windows.csproj
  GVFS/GVFS.FunctionalTests.Windows/Windows/Tests/SharedCacheUpgradeTests.cs
  GVFS/GVFS.FunctionalTests.Windows/Windows/Tests/WindowsDiskLayoutUpgradeTests.cs
  GVFS/GVFS.FunctionalTests.Windows/Windows/Tests/WindowsTombstoneTests.cs
  GVFS/GVFS.FunctionalTests/Tests/DiskLayoutVersionTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DehydrateTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/UpdatePlaceholderTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/DiskLayoutUpgradeTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/MacDiskLayoutUpgradeTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSHelpers.cs
  GVFS/GVFS.FunctionalTests/Tools/TestConstants.cs
  GVFS/GVFS.Mount/InProcessMount.cs
  GVFS/GVFS.PerfProfiling/ProfilingEnvironment.cs
  GVFS/GVFS.Platform.Mac/DiskLayoutUpgrades/DiskLayout18to19Upgrade_SqlitePlacholders.cs
  GVFS/GVFS.Platform.Mac/DiskLayoutUpgrades/MacDiskLayoutUpgradeData.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout12to13Upgrade_FolderPlaceholder.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout16to17Upgrade_FolderPlaceholderValues.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout18to19Upgrade_SqlitePlacholders.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/DiskLayout9to10Upgrade_BackgroundAndPlaceholderListToFileBased.cs
  GVFS/GVFS.Platform.Windows/DiskLayoutUpgrades/WindowsDiskLayoutUpgradeData.cs
  GVFS/GVFS.Platform.Windows/GVFS.Platform.Windows.csproj
  GVFS/GVFS.UnitTests.Windows/Windows/Virtualization/WindowsFileSystemVirtualizerTests.cs
  GVFS/GVFS.UnitTests/Common/Database/GVFSDatabaseTests.cs
  GVFS/GVFS.UnitTests/Common/Database/PlaceholderTableTests.cs
  GVFS/GVFS.UnitTests/Common/LegacyPlaceholderDatabaseTests.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockFileSystemCallbacks.cs
  GVFS/GVFS.UnitTests/Platform.Mac/MacFileSystemVirtualizerTests.cs
  GVFS/GVFS.UnitTests/Virtualization/FileSystemCallbacksTests.cs
  GVFS/GVFS.Virtualization/BlobSize/BlobSizes.cs
  GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.GitIndexParser.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.cs
  GVFS/GVFS/RepairJobs/BlobSizeDatabaseRepairJob.cs
  GVFS/GVFS/RepairJobs/PlaceholderDatabaseRepairJob.cs
  GVFS/GVFS/RepairJobs/RepairJob.cs
Labels: affects: performance, pr: refactoring

#1200 Mac kext testing: assert() integration
  ProjFS.Mac/PrjFS.xcodeproj/project.pbxproj
  ProjFS.Mac/PrjFSKextTests/HandleFileOpOperationTests.mm
  ProjFS.Mac/PrjFSKextTests/HandleOperationTests.mm
  ProjFS.Mac/PrjFSKextTests/KauthHandlerTests.mm
  ProjFS.Mac/PrjFSKextTests/KextAssertIntegration.h
  ProjFS.Mac/PrjFSKextTests/KextAssertIntegration.m
  ProjFS.Mac/PrjFSKextTests/MemoryTests.mm
  ProjFS.Mac/PrjFSKextTests/MessageTests.mm
  ProjFS.Mac/PrjFSKextTests/ProviderMessagingMock.cpp
  ProjFS.Mac/PrjFSKextTests/ProviderMessagingMock.hpp
  ProjFS.Mac/PrjFSKextTests/VirtualizationRootsTests.mm
  ProjFS.Mac/PrjFSKextTests/VnodeCacheTests.mm
  ProjFS.Mac/Scripts/Build.sh
Labels: affects: tests, domain: kext, platform: macOS
