Repository microsoft/VFSForGit, pull requests merged in 2019-07, with the labels that each got.

#1300 Update Git to include status deserialize fix
  GVFS/GVFS.Build/GVFS.props
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
Labels: affects: correctness, domain: git, type: bug

#1283 Incremental commit graph
  GVFS/GVFS.Build/GVFS.props
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.Common/Maintenance/PostFetchStep.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbWithoutSharedCacheTests.cs
  GVFS/GVFS.UnitTests/Maintenance/PostFetchStepTests.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
Labels: affects: performance, type: enhancement

#1285 Installer reliability
  GVFS/GVFS.Installer.Mac/scripts/postinstall
  GVFS/GVFS.Installer.Mac/scripts/preinstall
  GVFS/GVFS.Installer.Mac/uninstall_vfsforgit.sh
Labels: platform: macOS

#1328 Move Enlistment Directory For Functional tests to ~/GVFS.FT
  GVFS/GVFS.FunctionalTests/Settings.cs
  Scripts/Mac/RunFunctionalTests.sh
Labels: domain: catalina, platform: macOS

#1342 Update Git to include tracing updates
  GVFS/GVFS.Build/GVFS.props
Labels: affects: live-site, domain: git

#1340 PrjFSKextLogDaemon: Don't log every time a dropped kext message is detected
  ProjFS.Mac/PrjFSKextLogDaemon/PrjFSKextLogDaemon.cpp
Labels: affects: live-site, domain: kext, platform: macOS

#1375 Remove all TODO(POSIX) and TODO(Mac) comments.
  GVFS/GVFS.Common/FileSystem/IPlatformFileSystem.cs
  GVFS/GVFS.Common/ModifiedPathsDatabase.cs
  GVFS/GVFS.Common/NativeMethods.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbWithoutSharedCacheTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/WorkingDirectoryTests.cs
  GVFS/GVFS.NativeHooks.Common/common.posix.cpp
  GVFS/GVFS.Platform.Mac/MacFileSystemVirtualizer.cs
  GVFS/GVFS.Platform.POSIX/POSIXFileSystem.Shared.cs
  GVFS/GVFS.Platform.POSIX/POSIXFileSystem.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.Shared.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystem.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockPlatformFileSystem.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.cs
  GVFS/GVFS/CommandLine/CloneVerb.cs
  ProjFS.Mac/PrjFSKext/KauthHandler.cpp
  ProjFS.Mac/PrjFSLib/PrjFSLib.cpp
Labels: platform: linux, platform: macOS, pri1

#1380 GitProcess: Catch InvalidOperationException when setting priority class
  GVFS/GVFS.Common/Git/GitProcess.cs
Labels: affects: live-site, priority: dogfood, type: bug

#1381 Upgrade: Fix test flakiness around upgrade reminders
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GVFSUpgradeReminderTests.cs
  GVFS/GVFS.Hooks/Program.cs
Labels: affects: tests, type: test-reliability

#1382 Update Git to include more tracing updates
  GVFS/GVFS.Build/GVFS.props
Labels: affects: live-site, domain: git
