Repository microsoft/VFSForGit, pull requests merged in 2019-09, with the labels that each got.

#1507 Check the disposing flag in Dispose methods
  GVFS/GVFS.Common/GVFSContext.cs
  GVFS/GVFS.Common/Git/HashingStream.cs
  GVFS/GVFS.Service/GVFSService.Windows.cs
  GVFS/GVFS.Virtualization/Background/BackgroundFileSystemTaskRunner.cs
Labels: domain: user-mode, platform: windows, type: bug

#1323 Dehydrate folders
  GVFS/GVFS.Common/Database/GVFSDatabase.cs
  GVFS/GVFS.Common/Database/IPlaceholderCollection.cs
  GVFS/GVFS.Common/Database/PlaceholderTable.cs
  GVFS/GVFS.Common/Database/SparseTable.cs
  GVFS/GVFS.Common/LegacyPlaceholderListDatabase.cs
  GVFS/GVFS.Common/ModifiedPathsDatabase.cs
  GVFS/GVFS.Common/NamedPipes/NamedPipeMessages.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DehydrateTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSFunctionalTestEnlistment.cs
  GVFS/GVFS.Mount/InProcessMount.cs
  GVFS/GVFS.Platform.Mac/MacFileSystemVirtualizer.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystemVirtualizer.cs
  GVFS/GVFS.UnitTests/Common/Database/PlaceholderTableTests.cs
  GVFS/GVFS.UnitTests/Mock/Virtualization/FileSystem/MockFileSystemVirtualizer.cs
  GVFS/GVFS.Virtualization/FileSystem/FileSystemVirtualizer.cs
  GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
  GVFS/GVFS/CommandLine/SparseVerb.cs
Labels: domain: user-mode, type: enhancement

#1506 Mac installer preinstall failure
  GVFS/GVFS.Installer.Mac/scripts/preinstall
Labels: affects: reliability, domain: upgrade, platform: macOS, type: bug

#1498 Don't allow Executables to be Placeholders
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/BasicFileSystemTests.cs
  ProjFS.Mac/PrjFSLib/PrjFSLib.cpp
  ProjFS.Mac/Scripts/Build.sh
Labels: affects: correctness, platform: macOS

#1513 Sparse ui cleanup
  GVFS/GVFS/CommandLine/SparseVerb.cs
Labels: affects: polish, domain: user-mode, type: enhancement

#1492 Setting FileSystemCallback instance in FileSystemVirtualizer early
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/MountTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSHelpers.cs
  GVFS/GVFS.Platform.Mac/MacFileSystemVirtualizer.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystemVirtualizer.cs
  GVFS/GVFS.UnitTests/Mock/Virtualization/FileSystem/MockFileSystemVirtualizer.cs
  GVFS/GVFS.Virtualization/FileSystem/FileSystemVirtualizer.cs
  GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
Labels: affects: correctness, affects: mount-reliability, platform: macOS

#1511 Add prune argument to the sparse verb
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
  GVFS/GVFS/CommandLine/GVFSVerb.cs
  GVFS/GVFS/CommandLine/SparseVerb.cs
Labels: affects: polish, domain: user-mode, type: enhancement

#1518 [Merge to M158] Call multi-pack-index with --no-progress
  GVFS/GVFS.Build/GVFS.props
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.UnitTests/Maintenance/PackfileMaintenanceStepTests.cs
Labels: affects: mount-reliability, platform: linux, platform: macOS, platform: windows

#1517 Call multi-pack-index with --no-progress
  GVFS/GVFS.Build/GVFS.props
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.UnitTests/Maintenance/PackfileMaintenanceStepTests.cs
Labels: affects: mount-reliability, platform: linux, platform: macOS, platform: windows

#1520 Add sparse set and file option
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs
  GVFS/GVFS/CommandLine/SparseVerb.cs
Labels: affects: polish, domain: user-mode, type: enhancement

#1521 Add disable option to quickly get out of sparse mode
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs
  GVFS/GVFS/CommandLine/SparseVerb.cs
Labels: affects: polish, domain: user-mode, type: enhancement

#1514 Mac dtruss: Improved fstatat() and related syscall argument formatting
  Scripts/Mac/Tracing/dtruss
Labels: affects: live-site, platform: macOS

#1503 restore mixed-case prefetch folder list tests and tidy MirrorProviders
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbTests.cs
  GVFS/GVFS.FunctionalTests/Tests/GitCommands/GitRepoTests.cs
  MirrorProvider/MirrorProvider.Mac/MacFileSystemVirtualizer.cs
  MirrorProvider/MirrorProvider.Windows/WindowsFileSystemVirtualizer.cs
  MirrorProvider/MirrorProvider/FileSystemVirtualizer.cs
Labels: affects: tests

#1527 [releases/shipped] Configure VFS4G pkg installer to always install kext/'VFS For Git.app' regardless of version
  GVFS/GVFS.Installer.Mac/vfsforgit_components.plist
Labels: affects: reliability, blocking, domain: upgrade, platform: macOS

#1500 Windows native toasts
  GVFS/GVFS.Common/GVFSConstants.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GVFSUpgradeReminderTests.cs
  GVFS/GVFS.Installer.Windows/Setup.iss
  GVFS/GVFS.Service.UI/Data/ActionItem.cs
  GVFS/GVFS.Service.UI/GVFS.Service.UI.csproj
  GVFS/GVFS.Service.UI/GVFSServiceUI.cs
  GVFS/GVFS.Service.UI/GVFSToastRequestHandler.cs
  GVFS/GVFS.Service.UI/IToastNotifier.cs
  GVFS/GVFS.Service.UI/Program.cs
  GVFS/GVFS.Service.UI/WinToastNotifier.cs
  GVFS/GVFS.Service/GVFSService.Windows.cs
  GVFS/GVFS.Service/Handlers/INotificationHandler.cs
  GVFS/GVFS.Service/Handlers/NotificationHandler.Mac.cs
  GVFS/GVFS.Service/Handlers/NotificationHandler.Windows.cs
  GVFS/GVFS.Service/ProductUpgradeTimer.cs
  GVFS/GVFS.Service/RepoRegistry.cs
  GVFS/GVFS.UnitTests.Windows/GVFS.UnitTests.Windows.csproj
  GVFS/GVFS.UnitTests.Windows/Windows/ServiceUI/GVFSToastRequestHandlerTests.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
Labels: affects: polish, platform: windows, type: enhancement

#1526 Configure VFS4G pkg installer to always install kext/'VFS For Git.app' regardless of version
  GVFS/GVFS.Installer.Mac/vfsforgit_components.plist
Labels: affects: reliability, blocking, domain: upgrade, platform: macOS

#1529 [POSIX] convert Mac-specific functional tests to POSIX where viable
  GVFS/GVFS.FunctionalTests/Categories.cs
  GVFS/GVFS.FunctionalTests/FileSystemRunners/BashRunner.cs
  GVFS/GVFS.FunctionalTests/Program.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/BasicFileSystemTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/CloneTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GVFSLockTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SymbolicLinkTests.cs
  GVFS/GVFS.FunctionalTests/Tests/GitCommands/GitCommandsTests.cs
Labels: affects: tests, platform: linux, platform: macOS

#1413 [Linux] Revise functional tests for cross-device mounts
  GVFS/GVFS.FunctionalTests/Categories.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GVFSLockTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitFilesTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitMoveRenameTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerTestCase/ModifiedPathsTests.cs
  GVFS/GVFS.FunctionalTests/Tests/GitCommands/GitCommandsTests.cs
Labels: affects: tests, platform: linux
