Repository microsoft/VFSForGit, pull requests merged in 2019-11, with the labels that each got.

#1561 Functional test failures on Server 2016
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GitReadAndGitLockTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/HealthTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/UpdatePlaceholderTests.cs
  GVFS/GVFS.Platform.Windows/HResultExtensions.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystemVirtualizer.cs
  GVFS/GVFS.Virtualization/FileSystem/FSResult.cs
  GVFS/GVFS.Virtualization/Projection/GitIndexProjection.cs
Labels: affects: tests, platform: windows, type: test-reliability

#1582 Update Git to include sparse-checkout feature branch
  GVFS/GVFS.Build/GVFS.props
  GVFS/GVFS.Build/GenerateInstallScripts.cs
Labels: domain: git

#1578 Create shared cache folders with the same ACLs as repo folders
  GVFS/GVFS.Common/FileSystem/IPlatformFileSystem.cs
  GVFS/GVFS.Common/GVFSEnlistment.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/LocalCacheResolver.cs
  GVFS/GVFS.Platform.POSIX/POSIXFileSystem.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsFileSystem.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS.UnitTests/Mock/FileSystem/MockPlatformFileSystem.cs
  GVFS/GVFS/CommandLine/CloneVerb.cs
Labels: affects: reliability, platform: windows

#1594 GVFSVerb: explicitly disable new config settings
  GVFS/GVFS/CommandLine/GVFSVerb.cs
Labels: domain: git

#1596 Fix upgrade timer crash
  GVFS/GVFS.Service/ProductUpgradeTimer.cs
Labels: affects: live-site, affects: reliability, platform: windows

#1600 WindowsGitHooksInstaller: allow configuring hooks in local git config
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/MountTests.cs
  GVFS/GVFS.Platform.Windows/WindowsGitHooksInstaller.cs
Labels: affects: correctness, pri1, type: bug

#1601 sparse: don't warn about dirty files inside the sparse set
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
  GVFS/GVFS/CommandLine/SparseVerb.cs
Labels: domain: sparse, pri1

#1552 [Linux] use backing root in dehydrate functional tests
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DehydrateTests.cs
  GVFS/GVFS.FunctionalTests/Tools/GVFSFunctionalTestEnlistment.cs
Labels: platform: linux

#1605 HandleDehydrateFolders: update index using reset
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/DehydrateTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs
  GVFS/GVFS.Mount/InProcessMount.cs
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
Labels: domain: sparse, pri1, type: bug
