Repository microsoft/VFSForGit, pull requests merged in 2019-12, with the labels that each got.

#1607 sparse: check for not recursive matches when finding dirty files
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs
  GVFS/GVFS.UnitTests.Windows/GVFS.UnitTests.Windows.csproj
  GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs
  GVFS/GVFS/CommandLine/SparseVerb.cs
  GVFS/GVFS/Properties/AssemblyInfo.cs
Labels: domain: sparse, pri1

#1610 dehydrate: skip mount validation steps
  GVFS/GVFS/CommandLine/DehydrateVerb.cs
Labels: affects: performance, domain: sparse, pri2

#1615 [master] PostFetchStep: do not immediately delete expired commit-graph files
  GVFS/GVFS.Common/Git/GitProcess.cs
  GVFS/GVFS.UnitTests/Maintenance/PostFetchStepTests.cs
Labels: affects: performance, type: bug

#1597 Move config & upgrader files to ProgramFiles
  GVFS/GVFS.Common/FileSystem/PhysicalFileSystem.cs
  GVFS/GVFS.Common/GVFSPlatform.cs
  GVFS/GVFS.Common/ProductUpgrader.cs
  GVFS/GVFS.FunctionalTests/Program.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/GVFSUpgradeReminderTests.cs
  GVFS/GVFS.Hooks/HooksPlatform/GVFSHooksPlatform.Mac.cs
  GVFS/GVFS.Hooks/HooksPlatform/GVFSHooksPlatform.Windows.cs
  GVFS/GVFS.Installer.Windows/Setup.iss
  GVFS/GVFS.Platform.Mac/MacPlatform.cs
  GVFS/GVFS.Platform.POSIX/POSIXPlatform.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.Shared.cs
  GVFS/GVFS.Platform.Windows/WindowsPlatform.cs
  GVFS/GVFS.Service.UI/Program.cs
  GVFS/GVFS.Service/GVFSService.Windows.cs
  GVFS/GVFS.Service/Program.Mac.cs
  GVFS/GVFS.UnitTests/Mock/Common/MockPlatform.cs
  GVFS/GVFS/CommandLine/DiagnoseVerb.cs
  GVFS/GVFS/CommandLine/LogVerb.cs
Labels: affects: security, platform: windows

#1621 [Linux] functional test backing root and DotGVFSRoot fixes
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/CloneTests.cs
  GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/MountTests.cs
Labels: platform: linux

#1622 GVFSVerb: use flags for core.gvfs
  GVFS/GVFS.Build/GVFS.props
  GVFS/GVFS/CommandLine/GVFSVerb.cs
Labels: domain: git
